services:
  xbot:
    #build: .
    image: zhaohq828/xbot
    container_name: xbot
    network_mode: host
    volumes:
        - './services:/data/xbot/services'
        - './config.json:/data/xbot/config.json'
        - './local.db:/data/xbot/local.db'
